apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=Dockerfile",
            "--context=git://github.com/gimral/kaniko-deploy.git",
            "--context-sub-path=sample-beam-app",
            "--no-push",
            "--cache",
            "--cache-dir=/cache"]
    volumeMounts:
      - name: maven-storage
        mountPath: /roor/.m2
      - name: kaniko-cache
        mountPath: /cache
    resources:
      limits:
        memory: 512Mi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"
  restartPolicy: Never
  volumes:
    - name: kaniko-cache
      persistentVolumeClaim:
        claimName: kaniko-cache-claim
    - name: maven-storage
      persistentVolumeClaim:
        claimName: maven-claim