apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=Dockerfile",
            "--context=git://github.com/gimral/kaniko-deploy.git",
            "--context-sub-path=sample-beam-app",
            "--destination=gimral/kaniko-test",
            "--cache",
            "--cache-dir=/cache",
            "--cache-repo=gimral/kaniko-test-cache"]
    volumeMounts:
      - name: maven-storage
        mountPath: /root/.m2
      - name: kaniko-cache
        mountPath: /cache
      - name: docker-config
        mountPath: /kaniko/.docker
    resources:
      limits:
        memory: 1024Mi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"
  restartPolicy: Never
  volumes:
    - name: kaniko-cache
      persistentVolumeClaim:
        claimName: kaniko-cache-claim
    - name: maven-storage
      persistentVolumeClaim:
        claimName: maven-claim
    - name: docker-config
      projected:
        sources:
        - secret:
            name: regcred
            items:
              - key: .dockerconfigjson
                path: config.json