apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    # args: ["--verbosity=trace",
    #         "--dockerfile=Dockerfile",
    #         "--context=git@github.com:gimral/kaniko-deploy.git",
    #         "--context-sub-path=sample-beam-app",
    #         "--no-push"] 
    command:
      - executor --context git@github.com:gimral/kaniko-deploy.git --context-sub-path=sample-beam-app --dockerfile Dockerfile --no-push
  

    resources:
      limits:
        memory: 512Mi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"
  restartPolicy: Never