version: "2.2"
services:
    jobmanager:
        image: flink-sample
        ports:
            - "8081:8081"
        command: standalone-job --job-classname org.example.sideinput.SideInputTest --runner=FlinkRunner
        environment:
            - |
                FLINK_PROPERTIES=
                jobmanager.rpc.address: jobmanager
                parallelism.default: 2

    taskmanager:
        image: flink-sample
        depends_on:
            - jobmanager
        command: taskmanager
        scale: 1
        environment:
            - |
                FLINK_PROPERTIES=
                jobmanager.rpc.address: jobmanager
                taskmanager.numberOfTaskSlots: 2
                parallelism.default: 2
